<<<<<<< HEAD
# Generated by Django 2.1 on 2019-06-09 10:48
=======
# Generated by Django 2.2 on 2019-05-07 10:28
>>>>>>> 65654df3d1ea7560581e9c1c73c48966500cebd7

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='views',
        ),
    ]
