# Generated by Django 2.2 on 2019-06-02 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20190529_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='cover',
            field=models.ImageField(default='', upload_to='articles/covers/%Y%m', verbose_name='上传图片'),
        ),
    ]
