# Generated by Django 2.2 on 2019-06-09 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_article_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporter',
            name='avatar',
            field=models.ImageField(default='', upload_to='reporters/avatars/%Y%m', verbose_name='上传图片'),
        ),
        migrations.AddField(
            model_name='reporter',
            name='intro',
            field=models.CharField(default='', max_length=140),
            preserve_default=False,
        ),
    ]
