# Generated by Django 2.2 on 2019-06-09 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20190609_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='pageviews',
            field=models.IntegerField(default=100, verbose_name='页面浏览量'),
        ),
    ]
