# Generated by Django 2.2 on 2019-06-19 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_auto_20190611_1358'),
        ('news', '0007_auto_20190609_1125'),
    ]

    operations = [
    ]
