# Generated by Django 2.2 on 2019-06-20 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_merge_20190619_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='cover',
            field=models.ImageField(default='', max_length=500, upload_to='articles/covers/%Y%m', verbose_name='上传图片'),
        ),
    ]
