# Generated by Django 2.2 on 2019-07-28 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_article_real_pageviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_publish',
            field=models.BooleanField(default=False, verbose_name='是否发布'),
        ),
    ]
