# Generated by Django 2.2 on 2019-05-29 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='accounts',
            new_name='Account',
        ),
    ]
